### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by ishaangupte21** [sidharthponram916/gpacalculator#1]
When I tried to calculate my GPA using this application, it gave me 'NaN' as the result.
![image](https://user-images.githubusercontent.com/66740903/152239505-b9e6bf97-5ef8-484c-80ff-0404556ec771.png)

**Comment by sidharthponram916** [comment]
Refresh the page. Input all the fields listed and then click submit.

**Comment by sidharthponram916** [comment]
I will make an error handling for that later. Edit: I have just created the error handler. I am going to close the issue.
